.pragma library

function get_cards() {
    var dataArray = [
                [
                    "Farmacia",
                    "Medico",
                    "Inyeccion",
                    "Remedios",
                    "Receta",
                    "Turno"
                  ],
                  [
                    "Escorpion",
                    "Aguijon",
                    "Desierto",
                    "Alacran",
                    "Picar",
                    "Veneno"
                  ],
                  [
                    "Paloma",
                    "Ave",
                    "Pajaro",
                    "Plumas",
                    "Alas",
                    "Paz"
                  ],
                  [
                    "Cicatriz",
                    "Se\u00f1al",
                    "Marca",
                    "Herida",
                    "Piel",
                    "Huella"
                  ],
                  [
                    "Manzana",
                    "Comer",
                    "Sidra",
                    "Verde",
                    "Rojo",
                    "Fruta"
                  ],
                  [
                    "Autografo",
                    "Fan",
                    "Lapicera",
                    "Famoso",
                    "Firma",
                    "Nombre"
                  ],
                  [
                    "Opera",
                    "Cantar",
                    "Escena",
                    "Musica",
                    "Pavarotti",
                    "Tenor"
                  ],
                  [
                    "Timido",
                    "Verguenza",
                    "Rubor",
                    "Callado",
                    "Temeroso",
                    "Miedo"
                  ],
                  [
                    "Alarma",
                    "Robo",
                    "Casa",
                    "Banco",
                    "Atraco",
                    "Ladron"
                  ],
                  [
                    "Levadura",
                    "Masa",
                    "Pan",
                    "Harina",
                    "Cocinar",
                    "Royal"
                  ],
                  [
                    "Circulo",
                    "Anillo",
                    "Redondo",
                    "Compas",
                    "Linea",
                    "Curva"
                  ],
                  [
                    "Dracula",
                    "Conde",
                    "Sangre",
                    "Transilvania",
                    "Colmillos",
                    "Vampiro"
                  ],
                  [
                    "Soltero",
                    "Casado",
                    "Novio",
                    "Estado Civil",
                    "Despedida",
                    "Compromiso"
                  ],
                  [
                    "Pick Up",
                    "Camioneta",
                    "Auto",
                    "4 ruedas",
                    "Carga",
                    "F-100"
                  ],
                  [
                    "Enfermera",
                    "Doctor",
                    "Consultorio",
                    "Medico",
                    "Hospital",
                    "Blanco"
                  ],
                  [
                    "Rosa",
                    "Espinas",
                    "Flor",
                    "Pantera",
                    "Color",
                    "Rojo"
                  ],
                  [
                    "Futbol",
                    "Maradona",
                    "Deporte",
                    "Arco",
                    "Gol",
                    "Pelota"
                  ],
                  [
                    "Belleza",
                    "Concurso",
                    "Hermosa",
                    "Linda",
                    "Mujer",
                    "Salon"
                  ],
                  [
                    "Falcon",
                    "Auto",
                    "Ford",
                    "4 ruedas",
                    "Patrullero",
                    "Policia"
                  ],
                  [
                    "Castigo",
                    "Diciembre",
                    "Papa Noel",
                    "Villancicos",
                    "Arbolito",
                    "Nacimiento"
                  ],
                  [
                    "Conejo",
                    "Animal",
                    "Dientes",
                    "Orejas",
                    "Bugs Bunny",
                    "Zanahoria"
                  ],
                  [
                    "Moda",
                    "Ropa",
                    "Alta Costura",
                    "Onda",
                    "Temporada",
                    "Desfile"
                  ],
                  [
                    "Pimpollo",
                    "Capullo",
                    "Boton",
                    "Flor",
                    "Rosa",
                    "Cerrado"
                  ],
                  [
                    "Billiken",
                    "Anteojito",
                    "Revista",
                    "Infantil",
                    "Quiosco",
                    "Ni\u00f1os"
                  ],
                  [
                    "Humo",
                    "Smog",
                    "Fuego",
                    "Quemar",
                    "Cigarrillo",
                    "Chimenea"
                  ],
                  [
                    "Pasto",
                    "Verde",
                    "Cesped",
                    "Jardin",
                    "Hierba",
                    "Cortar"
                  ],
                  [
                    "Color",
                    "Amarillo",
                    "Tojo",
                    "Verde",
                    "Azul",
                    "Marron"
                  ],
                  [
                    "Vagabundo",
                    "Mendigo",
                    "Linyera",
                    "Ciruja",
                    "Pobre",
                    "Casa"
                  ],
                  [
                    "Bateria",
                    "Platillos",
                    "Instrumento",
                    "Musica",
                    "Ritmo",
                    "Bombo"
                  ],
                  [
                    "Calendario",
                    "Mes",
                    "Almanaque",
                    "Fecha",
                    "Dias",
                    "A\u00f1o"
                  ],
                  [
                    "Rating",
                    "Encuesta",
                    "Opinion",
                    "TV",
                    "Programa",
                    "Porcentaje"
                  ],
                  [
                    "Ataque",
                    "Asalto",
                    "Violencia",
                    "Agresion",
                    "Defender",
                    "Ofensiva"
                  ],
                  [
                    "Sirena",
                    "Pez",
                    "Canto",
                    "Mar",
                    "Cola",
                    "Mujer"
                  ],
                  [
                    "Crudo",
                    "Cocinar",
                    "Fuego",
                    "Cocido",
                    "Comida",
                    "Carne"
                  ],
                  [
                    "Desodorante",
                    "Transpiracion",
                    "Olor",
                    "Aerosol",
                    "Perfume",
                    "Axilas"
                  ],
                  [
                    "Boleto",
                    "Tren",
                    "Colectivo",
                    "Pasaje",
                    "Sacar",
                    "Micro"
                  ]
    ];

    return dataArray;
}

function shuffle(o){
    for(var j, x, i = o.length; i; j = parseInt(Math.random() * i), x = o[--i], o[i] = o[j], o[j] = x);
    return o;
};
